# Generated by Django 5.0.4 on 2024-06-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_time_event_date_posted_event_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Description of the event'),
        ),
    ]
