# Generated by Django 5.0.4 on 2024-07-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_signup_email_signup_phone_alter_signup_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='CRCRegister',
        ),
    ]
