# Generated by Django 5.0.4 on 2024-07-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_crcregister_crcclass_timetrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timetrack',
            name='crc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetrack',
            name='other',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetrack',
            name='service',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
