# Generated by Django 5.0.4 on 2024-08-05 03:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_project_description_alter_project_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crcclass',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=4096, null=True),
        ),
    ]
