# Generated by Django 5.0.4 on 2024-08-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_crcclass_description_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crcclass',
            name='image_file',
            field=models.ImageField(null=True, upload_to='classes/images'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_file',
            field=models.ImageField(null=True, upload_to='events/images'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_file',
            field=models.ImageField(null=True, upload_to='projects/images'),
        ),
    ]
